spring.application.name=backend
spring.application.name=wte-backend
server.port=8080
wte.frontend-origins=http://localhost:5173,https://wte-whattoeat.netlify.app
wte.recipe-source-url=https://www.10000recipe.com/recipe/list.html
